### ISSUE TITLE
Azure Devops Pipeline with a new MSTest runner 3.2.0

### ISSUE THREAD

**Issue by SymbioticKilla** [microsoft/testfx#2175]
Hi,

can anybody share pipeline steps to build/run tests with code coverage and test results?
Or perhaps anybody can help me modify my pipeline to support MSTestRunner?
Thanks!

This is a new project with 3.2.0 runner. What should I change in the pipeline to make it work?
```csproj
  <PropertyGroup>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.0.0" />
    <PackageReference Include="MSTest" Version="3.2.0" />
  </ItemGroup>
 </PropertyGroup>
```

My pipeline:
```yaml
 - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: "build"
      projects: '**/Solution.sln'
      arguments: '-c Release'

  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    continueOnError: true
    inputs:
      command: 'test'
      projects: '**/Solution.sln'
      arguments: '-c Release --results-directory "$(Build.SourcesDirectory)/TestResults/Coverage/" --collect "XPlat Code Coverage" --logger trx'
      publishTestResults: false

  - task: reportgenerator@5
    displayName: Generate code coverage report
    inputs:
      reports: '$(Build.SourcesDirectory)/TestResults/Coverage/*/coverage.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)/TestResults/CoverageReport'

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/TestResults/CoverageReport/Cobertura.xml"
      reportDirectory: "$(Build.SourcesDirectory)/TestResults/CoverageReport"

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Build.SourcesDirectory)/TestResults/Coverage'
      mergeTestResults: true

```

**Comment by Evangelink** [comment]
Hi @SymbioticKilla,

MSTest runner has a compatibility layer with the past so you could run your pipeline as-is (you won't get the benefit of the new features/perfs...). 

If you want to take full advantage of the runner, you should be following this doc page for [enabling dotnet test with the runner](https://learn.microsoft.com/dotnet/core/testing/unit-testing-mstest-runner-integrations#dotnet-test---mstest-runner-mode).

For the code coverage, if you want to use coverlet (as there is currently no specific adapter), you will have to use the global tool. Please refer to coverlet doc page https://github.com/coverlet-coverage/coverlet#net-global-tool-guide-suffers-from-possible-known-issue. If you don't mind using Microsoft Code Coverage (which we recommend - check out this article for some of the reasons https://devblogs.microsoft.com/dotnet/whats-new-in-our-code-coverage-tooling/?utm_content=buffer9eae6&utm_medium=social&utm_source=linkedin.com&utm_campaign=buffer), then you can use the following configuration.

Project
```csproj
  <PropertyGroup>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.0.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.10.1" />
    <PackageReference Include="MSTest" Version="3.2.0" />
  </ItemGroup>
 </PropertyGroup>
```

My pipeline:
```yaml
 - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: "build"
      projects: '**/Solution.sln'
      arguments: '-c Release'

  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    continueOnError: true
    inputs:
      command: 'test'
      projects: '**/Solution.sln'
      arguments: '-c Release -p:TestingPlatformCommandLineArguments=" --results-directory \"$(Build.SourcesDirectory)/TestResults/Coverage/\" --report-trx --coverage --coverage-output-format covertura "'
      publishTestResults: false

  - task: reportgenerator@5
    displayName: Generate code coverage report
    inputs:
      reports: '$(Build.SourcesDirectory)/TestResults/Coverage/*/coverage.cobertura.xml'
      targetdir: '$(Build.SourcesDirectory)/TestResults/CoverageReport'

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/TestResults/CoverageReport/Cobertura.xml"
      reportDirectory: "$(Build.SourcesDirectory)/TestResults/CoverageReport"

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Build.SourcesDirectory)/TestResults/Coverage'
      mergeTestResults: true

```
