### ISSUE TITLE
TestContext.WriteLine() interleaves logs

### ISSUE THREAD

**Issue by AbhishekMarda** [microsoft/testfx#2430]
## Describe the bug
I saw existing an bug that was closed : https://github.com/Microsoft/testfx/issues/386
This is similar, but in a slightly different context.

Essentially, when using TestContext.WriteLine() in a base class, it seems to not be thread-safe and interleaves logs from tests that exist in the inherited classes. 

I found this when running in Azure Pipelines as part of a VSTest@2 task:
```YAML
    - task: VSTest@3
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\testbin\**\*Tests.dll
        runSettingsFile: $(REPOROOT)\test\test.runsettings
        runInParallel: true
        publishTestResults: true
        testFilterCriteria: ${{ parameters.test_filter }}
```

## Steps To Reproduce
In the CSproj, the versions are:
```xml
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
```
The runsettings file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<!-- MSTest adapter -->
	<MSTest>
		<CaptureTraceOutput>True</CaptureTraceOutput>
		<Parallelize>
			<Workers>4</Workers>
		</Parallelize>
	</MSTest>
</RunSettings>
```
Let there be a TestBase.cs
```csharp
[TestClass]
public abstract class TestBase 
{
  public TestContext TestContext { get; set; }

  [TestInitialize]
  public void Init()
  { // do something, but just mentioning that all inherited classes have the same init method, in case that has an effect
  }
 
  protected LogMessage(string message)
  {
    TestContext.WriteLine($"{TestContext.TestName} | {message}");
  }
}
```
Say there's two classes
```csharp
[TestClass]
public class MyTestClass1 : TestBase
{
  [TestMethod]
  public void Method1()
  {
     for(int i=0; i<10; i++)
     {
        LogMessage("Hello Method1!");
        Thread.Sleep( (new Random()).Next(1000,10000) );
     }
  }
}
```
```csharp
[TestClass]
public class MyTestClass2 : TestBase
{
  [TestMethod]
  public void Method2()
  {
     for(int i=0; i<10; i++)
     {
        LogMessage("Hello Method2!");
        Thread.Sleep( (new Random()).Next(1000,10000) );
     }
  }
}
```
## Expected behavior
For each class method, the output in Azure DevOps should be associated with its own method. I
For eg, for Method1:
```txt
Method1 | Hello Method1
Method1 | Hello Method1
...
```
and similar for Method2.

## Actual behavior

Logs for Method1 will look as follows:
```txt
Method1 | Hello Method1
Method1 | Hello Method1
Method2 | Hello Method2
```
And something similar for Method2, where logs will be dispersed all across the different tests. The number of logs will still be 10+10=20, but one logfile may have 15 logs and the other may have 5, and which test's log they end up in is completely random.

## Additional context
The TestContext is being set correctly, since the method name is being captured correctly and is a separate instance in each class instance. However, it seems that WriteLine() is using the same stream or is not thread safe? 
The logger being used is trx as part of the VSTest task.
