### ISSUE TITLE
Usage of MSTest Runner in AzDO pipelines

### ISSUE THREAD

**Issue by fforjan** [microsoft/testfx#2500]
From #2489, there was a remark from @MarcoRossignoli to use the MStest Runner.

Following a quick look at https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-runner-intro?tabs=continuous-integration#run-and-debug-tests the information seems light.

In our current pipelines, we are doing something like this :
```yml
  - task: VSTest@2
    displayName: 'Run .net 472 tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        Source\**\net472\*Tests.dll
      codeCoverageEnabled: true
      testRunTitle: '$(Build.DefinitionName) - net472'

  - task: VSTest@2
    displayName: 'Run .net 6 tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        Source\**\net6.0*\*Tests.dll        
      codeCoverageEnabled: true
      testRunTitle: '$(Build.DefinitionName) - net460'
```

Which means:
it runs all the tests found in our solution, generate 1 test run - meaning 1 test run result, 1 TRX and 1 Coverage file in the test pipelines - for both our .NET Framework and .Net 6

it is not clear from the documentation
```
- task: CmdLine@2
  displayName: "Run Contoso.MyTests"
  inputs:
    script: '.\Contoso.MyTests\bin\Debug\net8.0\Contoso.MyTests.exe'
```

How can we achieve the same result which is one test run for all each frameworks meaning 1 run result, 1 TRX and 1 Coverage for both platforms .net fwk and .net 6  ?
- we have 50+ test projects , some partially only net472 -hello WPF related tests, some both net472 and net6.0 so wildcard are welcome
- in order to simplify our analysis and reports, having one test run instead of 50 TRX and Coverage file is quite important.
