### ISSUE TITLE
3.4 is not working with Fakes

### ISSUE THREAD

**Issue by Evangelink** [microsoft/testfx#3003]
3.4.0 and 3.4.1 are both not working while 3.3.1 was fine for this scenario:

- .NET8 ProjectX
- .NET8 test ProjectY which uses [Microsoft Fakes](https://learn.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2022) for project X
- Build on Azure DevOps using [VSBuild@1](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vsbuild-v1?view=azure-pipelines).
- Run ProjectY

The Fakes assemblies cannot be resolved, each test that uses them outputs:

`System.IO.FileNotFoundException: Could not load file or assembly 'ProjectX.Fakes, Version=x.x.x.x, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`.

Where ProjectX.Fakes.dll is present in the output folder next to ProjectY.exe.

_Originally posted by @Rans4ckeR in https://github.com/microsoft/testfx/issues/2922#issuecomment-2134633254_

**Comment by Rans4ckeR** [comment]
> Could you please provide some more details? Are you using `VSTest` or `MSTest runner` to run the tests? Is the issue happening only on VS? Would it be possible for you to create a small reproducer?
> 
> cc @drognanar @jakubch1

I can only reproduce it on Azure DevOps, not locally;

Pipeline bits
```
pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Agent.Source.Git.ShallowFetchDepth: 0

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'

- task: CmdLine@2
  displayName: 'Run tests'
  inputs:
    script: '.\TestProject\bin\Release\net8.0\TestProject.exe --report-trx --coverage'
```

ProjectX
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TestProject" />
    <InternalsVisibleTo Include="ProjectX.Fakes" />
  </ItemGroup>
</Project>
```

TestProject
```
<Project Sdk="MSTest.Sdk/3.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FakesAssemblies\**" />
    <EmbeddedResource Remove="FakesAssemblies\**" />
    <None Remove="FakesAssemblies\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.QualityTools.Testing.Fakes" Version="17.5.0-beta.23060.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectX\ProjectX.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalDesignTimeBuildInput Remove="FakesAssemblies\**" />
  </ItemGroup>
</Project>
```

TestProject\Fakes\ProjectX.fakes
```
<Fakes xmlns="http://schemas.microsoft.com/fakes/2011/">
  <Assembly Name="ProjectX"/>
  <StubGeneration>
    <Clear/>
    <Add Interfaces="true" Namespace="ProjectX!"/>
  </StubGeneration>
  <ShimGeneration Disable="true"/>
</Fakes>
```

If I build & run the tests locally in VS it works. Both running the tests in VS and running the .exe directly works.
If I copy the binaries produced from the pipeline to my local machine I get the same assembly resolution error.

Also tried this in the pipeline with the same result:
- Use dotnet test instead of running the .exe
- Downgrading `Microsoft.QualityTools.Testing.Fakes` to the latest stable
- Target .NET9 instead of .NET8
