### ISSUE TITLE
DataRow execution is published as 'unspecified' with VSTest@3 task for Test plan

### ISSUE THREAD

**Issue by gasparnagy** [microsoft/testfx#4738]
## Describe the bug

We are using the VSTest@3 task in Azure DevOps for executing the MsTest test associated to Test Cases which having data rows in the test method (`[DataRow]`). 

Based on the issue suggestion at #992, we have disabled source discovery using `[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]`

When we run the pipeline, it logs all data rows as executed, but in the TestRun it is reported as a single test with 'unspecified' result. (In the TRX file that is attached to the TestRun all data row execution is recorded.)

When I downgrade MSTest.TestAdapter and MSTest.TestFramework to v2.2.3 (and remove `[TestDataSourceDiscovery]`) it works fine.

## Steps To Reproduce

1. Create a new MsTest project.
2. Add a test method like.

```
        [DataTestMethod]
        [DataRow(42)]
        [DataRow(43)]
        public void TestMethod1(int value)
        {
            Console.WriteLine($"Value: {value}");
        }
```

3. Add to the project: `[assembly: TestDataSourceDiscovery(TestDataSourceDiscoveryOption.DuringExecution)]`
4. Create a TestPlan, a Test Suite and a Test Case in ADO
5. Associate the `TestMethod1` to the Test Case
6. Create a pipeline that builds the project and runs the tests based on the TestPlan/TestSuite:

```
- task: VSTest@3
  displayName: 'VsTest - testSuite'
  inputs:
    testSelector: testPlan
    testPlan: 552255
    testSuite: 552257
    testConfiguration: 15
    testRunTitle: 'CI1-Plan'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
```

7. Run pipeline and check "Tests" tab

## Expected behavior

Displays the data row test as sub-tests, like with MsTest 2.2.3:

![Image](https://github.com/user-attachments/assets/691a92a8-7f47-4477-9066-c9b4b335f211)

## Actual behavior

It is shown as 'Unspecified':

![Image](https://github.com/user-attachments/assets/c21c5241-61f4-4dc8-8b9c-8a51dfd1cf42)

Also in the related Test Run:

![Image](https://github.com/user-attachments/assets/5061a3e6-1471-4aff-9a95-2a1cd2930d91)

## Additional context

I have also tried with VSTest@2, made no difference.
